### ISSUE TITLE
HTML table isn't being displayed correctly

### ISSUE THREAD

**Issue by fmmesen** [onizet/html2openxml#123]
Hello!
When I have a simple html table (please check the following)

<table>
<thead>
<tr>
<th>Syntax</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>Header</td>
<td>Title</td>
</tr>
<tr>
<td>Paragraph</td>
<td>Text</td>
</tr>
</tbody>
</table>

In the docx file is being displayed like this 
<img width="80" alt="Screen Shot 2022-10-04 at 10 55 46" src="https://user-images.githubusercontent.com/110683318/193920097-06e5a0de-a1d0-4cb7-882f-2b020678b7dd.png">

**Comment by onizet** [comment]
Hi, I'm intensively working on v3 at the moment, I will take a look at this item too.

**Comment by fmmesen** [comment]
Oh! Well... the problem was using a MacOs word, everything was working when I went back to word in windows

**Comment by onizet** [comment]
I'm closing this issue as this is only related to Apple Pages.

Unfortunately Apple Pages struggles with table in general. Combining row span and col span messed up.
The Width=Auto is absolutely not respected. It's hard for this converter to guess the width of the cells, it depends on the font size and font family.
