### ISSUE TITLE
Non integer font sizes specified with <FONT size=

### ISSUE THREAD

**Issue by berthendrickx** [onizet/html2openxml#129]
I noticed that if you specify FONT size="9.5pt" this is converted to a font size of 9 in Word, instead of 9,5

I suggest a small change to correct for this in Unit.cs:

```
public double ValueInPoint
{
	get { return (double) (type == UnitMetric.Point ? Math.Round(this.value * 2) / 2 : (float) valueInEmus / 12700L); }
}
```

**Comment by onizet** [comment]
I have committed this code. Thanks for reporting
