### ISSUE TITLE
HtmlDocumentStyle changes how styles are loaded

### ISSUE THREAD

**Issue by pauldbentley** [onizet/html2openxml#134]
Commit 3d8dbfbd304510d1a704172dbc95b72a386de61a seems to change how the styles are loaded.

Previously we would get for example:

"GridTable5Dark-Accent5"
"Grid Table 5 Dark Accent 5"

But after this commit we only get:

"Grid Table 5 Dark Accent 5"

Is this intentional?  It is causing issues styling tables with a css class="GridTable5Dark-Accent5"

**Comment by onizet** [comment]
After testing, it seems v3 is now correctly handling the style names as before. Sorry about that, I will enforce a new rule to ensure submitted PR respect the Unit Testing
