### ISSUE TITLE
The specified argument is not a child of this element

### ISSUE THREAD

**Issue by pauldbentley** [onizet/html2openxml#135]
This exception is raised when processing a table with a class of a known style.

The exception is raised in TableStyleCollection.css inside ApplyTags with the call to properties.AddChild(tag.CloneNode(true));

This was changed in ee956a94af1450fb85329cc3ac33c32e31dea1b8 when the reflection use was remove.

I've attached a console app to reproduce

[ConsoleApp2.zip](https://github.com/onizet/html2openxml/files/12093161/ConsoleApp2.zip)

**Comment by preetidulloo3bits** [comment]
Hi, I am facing the same issue. Any solution?
