### ISSUE TITLE
Not compatible with OpenXML 3.01

### ISSUE THREAD

**Issue by hankpotter** [onizet/html2openxml#137]
got object undefined error when calling ParseHtml.
Work with version 2.15.0. Not try other vesion.

**Comment by onizet** [comment]
They have introduced lots of breaking changes; I'm working to upgrade this library

**Comment by ryanlin1986** [comment]
Can't wait! thanks for your great work!

**Comment by onizet** [comment]
Hi, I have published v2.4 on nuget

**Comment by ryanlin1986** [comment]
Thanks a lot, great work!
