### ISSUE TITLE
Could not load file or assembly 'HtmlToOpenXml, Version=2.4.0.0, Culture=neutral, PublicKeyToken=6ad79d83e2b60e63' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

### ISSUE THREAD

**Issue by tomas-net** [onizet/html2openxml#138]
When installing the latest nuget package into ASP.NET WebForms project (targeting .NET Framework 4.8) I am getting this error:

`Could not load file or assembly 'HtmlToOpenXml, Version=2.4.0.0, Culture=neutral, PublicKeyToken=6ad79d83e2b60e63' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)`

**Comment by NickHodgeBB** [comment]
Had the same error when building a ASP.NET MVC Solution.

**Comment by IanMacro** [comment]
I've also got the same issue, and had to downgrade to v2.3.0.

**Comment by onizet** [comment]
I'm working on MacOS and it seems building .Net Framework 4.x DLL doesn't work well.
I will remove the support for that framework as you could reference the NetStandard 2.0 version.

**Comment by tomas-net** [comment]
@onizet Thank you for fast response, but problem still exists

`Could not load file or assembly 'HtmlToOpenXml, Version=2.4.1.0, Culture=neutral, PublicKeyToken=6ad79d83e2b60e63' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)`
