### ISSUE TITLE
<strong>, <i>, <u> with custom style

### ISSUE THREAD

**Issue by k59319** [onizet/html2openxml#14]
`<strong>,<i>, <u>` tags can also have 'style' attribute with custom colors and other formatting. At this moment your library ignores custom styles in 'strong' and other tags. 
Example html:
```
  <p>
    <span style="color:rgb(255, 0, 0)">test span</span>
    <strong style="color:rgb(255, 0, 0)">test strong</strong>
  </p>
```
After converting to Wml the text inside 'span' tag will have red color as specified in html but text inside 'strong' tag won't. I took the example html from real world. It was user input from the SharePoint rich text field.

**Comment by onizet** [comment]
I was indeed very curious about your commit and it was deserving more testing before I merge it.
For reference, I use a slightly more complicated HTML than yours for testing:

```
<p style='color:red'>
   <b style='color:green'>Some text in <i>bold</i> (and <i style='color:gray'>gray</i>)</b> 
   <b>and</b> some don't but instead <i>in italics.</i>.
</p>
```
