### ISSUE TITLE
Table borders not rendering properly

### ISSUE THREAD

**Issue by PeteSmithDev** [onizet/html2openxml#144]
Table borders don't render properly.

This can be repeated using example code from the supplied documentation.
- C# code from the [How to start?](https://github.com/onizet/html2openxml/wiki/HowToStart) page
- Template HTML from the [Table](https://github.com/onizet/html2openxml/wiki/Table) page

This should render the tables as shown in the documentation:
![image](https://github.com/onizet/html2openxml/assets/141425625/794e0276-28ca-4ef1-93bc-55ddd22cf6cd)

However, it renders tables that looks like this in MS Word 365 version 2405:
![image](https://github.com/onizet/html2openxml/assets/141425625/52fcd5ab-840f-4bc9-8af3-a2f5ba195f9b)

**Comment by onizet** [comment]
Hello, thank you for your message.
I was already working on the table border widths these latest days, so just linking those together.
I'm actively working on v3 which will solve lots of issues raised on numbering and table. Just a couple of additional weeks of patience. Thank you
