### ISSUE TITLE
Table of Contents (Hrefs) do not work.

### ISSUE THREAD

**Issue by paulius-petkus** [onizet/html2openxml#150]
**Describe the bug**
Html page has "table of contents" - hrefs to other parts of the same Html document. After the HTML --> DOCX conversion, table of contents lines navigate not to the concrete section, but to the very beginning of the document.

**Expected behavior**
Hrefs should navigate into sections.

**Repro**
```csharp
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using HtmlToOpenXml;
.
.
.

    static void ConvertHtmlToDocx(string html, string filePath)
    {
        using var wordDoc = WordprocessingDocument.Create(filePath, WordprocessingDocumentType.Document);
        // Add a main document part.
        MainDocumentPart mainPart = wordDoc.AddMainDocumentPart();

        // Create the document structure and add some text.
        mainPart.Document = new Document();
        var body = new Body();
        mainPart.Document.Append(body);

        var converter = new HtmlConverter(mainPart);
        converter.ParseHtml(html);
        
        mainPart.Document.Save();
    }
```
attaching the failing HTML (source):
[big.zip](https://github.com/user-attachments/files/16066688/big.zip)

result Docx:
[output.docx](https://github.com/user-attachments/files/16066700/output.docx)

**Comment by onizet** [comment]
Hello, nothing better than working on a real use case! The current implementation is looking for the target using the `id`attribute. According to W3C, `name` attribute is obsolete but is still supported by modern browser.
I will amend the code to support this too.

**Comment by onizet** [comment]
Thank you again for your real sample, it helps me to troubleshoot a lots on whitespaces and headings.
You can delete the attachment as it may contains confidential data.
