### ISSUE TITLE
Converting "line1<div>line2<br><div>line3<br></div></div>" results in 4 lines instead of 3 lines

### ISSUE THREAD

**Issue by PRSHGR** [onizet/html2openxml#158]
When converting `line1<div>line2<br><div>line3<br></div></div>` resulting file looks like this:
![obraz](https://github.com/user-attachments/assets/b0b2cdd2-5108-4c8b-8743-4047daa6a8db)
Same HTML opened in browser looks like this:
![obraz](https://github.com/user-attachments/assets/749958a1-e03c-4c99-9afb-0ddb9cc25511)
Looks like `<DIV>` must start in new line, but when it is already in new line, then there is no need to create yet another line

[HtmlTest.docx](https://github.com/user-attachments/files/16837739/HtmlTest.docx)

**Comment by PRSHGR** [comment]
Thank you for very prompt fix.

Are there plans for new release with this fix included?

**Comment by onizet** [comment]
This is published now

**Comment by PRSHGR** [comment]
Thank you!
