### ISSUE TITLE
Basic header or footer definition will crash the conversion when image are encountered

### ISSUE THREAD

**Issue by onizet** [onizet/html2openxml#159]
**Describe the bug**
Cross-reference from #CervantesSec/cervantes/issues/51

**Repro**
This line of code is the culprit: `mainPart.AddNewPart<HeaderPart>()`
The definition of the header is incomplete, thus accessing mainParts.HeaderParts.First().Header will throws a null reference exception.

**Comment by jstangle** [comment]
Hi @onizet, I just tested the latest release. Unfortunately, the images in the header and footer of the HTML are not being displayed in the DOCX report.

**Comment by onizet** [comment]
This current issue is fixed. What you are requesting is different, it's the ability to convert html into header and footer. From day 1 I created this library, only the body was officially supported.

I will create a separate work item for that purpose
