### ISSUE TITLE
Ability to convert into header/footer

### ISSUE THREAD

**Issue by onizet** [onizet/html2openxml#162]
Currently, the implementation only support parsing html into the body (document MainPart).
The OpenXml SDK is slightly different (for example, you cannot have footnote reference in header/footer, or having a clickable image etc...)

90% of the time, users insert the parsed Html inside their own docx template, thus reusing a predefined header and footer.

I'm creating this work item for follow-up on the new feature request.
I'm thinking of providing methods such : `converter.ParseHeader()` `converter.ParseFooter()` and `converter.ParseBody()` (instead of `converter.ParseHtml` which is confusing)

Another solution, would be to automatically detect the first `body > header` and the last `body > footer`. Or more specifically, [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role), any element with the ARIA role="banner"  specifies:

> By default, the HTML's `<header>` element has an identical meaning to the banner landmark, unless it is a descendant of `<aside>`, `<article>`, `<main>`, `<nav>`, or `<section>`, at which point `<header>` exposes a generic role, and not the equivalent of the site-wide banner.

What are your though? @mesquidar  @jstangle

**Comment by mesquidar** [comment]
Hi @onizet thanks for your update :)

I think provide different methods as you comment converter.ParseHeader() ,converter.ParseFooter() and converter.ParseBody() can be a good solution. In my opinion it provides the most flexibility, clarity and control over where the parsed content is inserted

**Comment by jstangle** [comment]
I agree, breaking it down into converter.ParseHeader(), converter.ParseFooter(), and converter.ParseBody() seems like the best solution. It might help resolve the issue more effectively – but whatever works best for you guys!
