### ISSUE TITLE
Some formats are missing

### ISSUE THREAD

**Issue by AlirezaAhmadiRad** [onizet/html2openxml#17]
Hello

Please find [link](https://1drv.ms/f/s!Alj_FDyopEuRgtlUBSmaMFoav2fEzA) of an Html file and result of its conversion to docx. As you can see, most of formattings like text formattings and borders are missing. What can I do to have these formattings effective?

Thanks

**Comment by onizet** [comment]
Hi, 

It's like no formatting has been applied.

Just to be sure, did you use the library from nuget?
If so, I'm sorry to ask, but could you try with the [release version from codeplex](http://html2openxml.codeplex.com/downloads/get/1528569)?
I'm in the middle of upgrading the Nuget version (which is very old) and support .Net Core.

Please beware that the col/colgroup tag are not supported.

**Comment by AlirezaAhmadiRad** [comment]
Thanks for response.
I downloaded from the link you provided and now I have the problem that it needs OpenXMl v 2.5.5631 while I'm using version 2.7.2.
For this reason, I had downloaded the source file and modified references manually. Previous package was v1.6 and this new link of yours is also v 1.6, so, I had used the correct version.

**Comment by AlirezaAhmadiRad** [comment]
Hello,
Any action/modification on the way for this issue? Is there any modification necessary to my HTML?
Thanks

**Comment by onizet** [comment]
This is clearly a bug on my side. I have add it to the backlog and will investigate more intensively on it.

**Comment by AlirezaAhmadiRad** [comment]
Thanks
