### ISSUE TITLE
Attribute align and margin: auto don't work

### ISSUE THREAD

**Issue by methalox** [onizet/html2openxml#171]
It doesn't align the element when parsing its "align" attribute.

`<p align="center">example</p>`

Also, images don't get centered when using margin auto.

`<p><img style="display: block; margin-left: auto; margin-right: auto;" src="/images/example.png" width="310" height="220"></p>`.

**Comment by onizet** [comment]
Hi @methalox, `align` is for `table`. Use `text-align` instead.

I'm aware that margin auto doesn't work but please remember that Html layout is far more powerful than what OpenXml can provide. I will put it in my investigation list but with no garantee of success.
