### ISSUE TITLE
Convertion skips some child items in text

### ISSUE THREAD

**Issue by plmarzi** [onizet/html2openxml#173]
Hi

So we are trying to use this library to convert Azure devops work items into openXML and merge them into word file.
I have noticed that some of text is missing if text is child or subchild:
![image](https://github.com/user-attachments/assets/70601831-9165-4923-8750-6de88addc3e5)
This is example of outcome word file:
![image](https://github.com/user-attachments/assets/3984b8e9-dfe9-4f1f-9d42-7d236ab224b2)

I have also noticed that ti can be fixed with that:

**Original**

`<ol>
<li><span lang="EN-US">The system shows the screen as pictured on the <b>Design 1</b></span></li>
<li>User selects between the two options:</li>
<ol>
<li><span>If "Call Support", then a pop-up with contact information appears (<b>Design 2</b>)</span></li>
<li><span>If "Cancel", then the user is transferred to the Get Started screen <a href="
https://dev.azure.com/coloplast/2c8e8844-d506-45b7-8286-5ebbb8e34aa4/_workitems/edit/58252"
data-vss-mention="version:1.0">#58252</a></span></li>
</ol>
</ol>`

**Fixed**

`<ol>
<li><span lang="EN-US">The system shows the screen as pictured on the <b>Design 1</b></span></li>
<li>User selects between the two options:</li>
<li>
<ol>
<li><span>If "Call Support", then a pop-up with contact information appears (<b>Design 2</b>)</span></li>
<li><span>If "Cancel", then the user is transferred to the Get Started screen <a href="
https://dev.azure.com/coloplast/2c8e8844-d506-45b7-8286-5ebbb8e34aa4/_workitems/edit/58252"
data-vss-mention="version:1.0">#58252</a></span></li>
</ol>
</li>
</ol>`

Anybody using this library came across this problem?

**Comment by onizet** [comment]
Hello, I notice that your original version, the nested `ol` is not part of a `li` element:

```html
<ol dir="auto"><p dir="auto"></p>
  <li><span lang="EN-US">The system shows the screen as pictured on the <b>Design 1</b></span></li>
  <li>User selects between the two options:</li>
  <ol dir="auto">
    <li><span>If "Call Support", then a pop-up with contact information appears (<b>Design 2</b>)</span></li>
    <li><span>If "Cancel", then the user is transferred to the Get Started screen #58252</span></li>
  </ol>
</ol>
```

while correct version should have been:

```html
<ol dir="auto"><p dir="auto"></p>
  <li><span lang="EN-US">The system shows the screen as pictured on the <b>Design 1</b></span></li>
  <li>User selects between the two options:
    <ol dir="auto">
      <li><span>If "Call Support", then a pop-up with contact information appears (<b>Design 2</b>)</span></li>
      <li><span>If "Cancel", then the user is transferred to the Get Started screen #58252</span></li>
    </ol>
  </li>
</ol>
```

Is this a html code you have generated or you got this as-is from the ADO markdown?

**Comment by onizet** [comment]
After some testing on my side, I have been able to reproduce on ADO. This is very unfortunate that they don't respect the W3C standard. I have added support for that behaviour in the converter.

**Comment by plmarzi** [comment]
Thank You for quick help! This is great!
