### ISSUE TITLE
Apply word break

### ISSUE THREAD

**Issue by VPantaleo** [onizet/html2openxml#174]
Hi, 

how can i apply a word break in html to word conversion ?

Thanks

**Comment by onizet** [comment]
Hello, to which style do you refer to
- text-wrap
- word-wrap
What do you want to achieve? It's not supported yet but happy to add that feature

**Comment by VPantaleo** [comment]
Hi,

Hi, thanks for replying, I need the word-wrap, but i use .net 6.0 
you can ?

Thanks

**Comment by onizet** [comment]
I was playing around with Word. it tooks me some time to realise I have to use the "Layout > Hyphenation"
Is this what you are looking for?
![image](https://github.com/user-attachments/assets/293b8b45-42e6-4f98-8344-d033de8b0eb8)

**Comment by VPantaleo** [comment]
Hi, 

I have testing 

HtmlConverter converter = new HtmlConverter(mainPart);
Body body = mainPart.Document.Body;
converter.HtmlStyles.DefaultStyle = converter.HtmlStyles.GetStyle("Hyphenation");

but not working.

![Immagine 2024-11-14 172716](https://github.com/user-attachments/assets/53abc8df-5ea9-40dd-b5af-03dec74d71c8)

**Comment by VPantaleo** [comment]
Hi, 

thanks for your answers, 

but how can i apply the css on <p> ?

Thanks

**Comment by onizet** [comment]
This is not yet supported in this library. But if you confirm what you are looking for refers to the "auto hyphenation" feature, I'm happy to implement it.

**Comment by VPantaleo** [comment]
Hi, I solved the problem by removing the tag &nbsp; from the initial html document. 
With the document without &nbsp; word correctly performs word separation.
