### ISSUE TITLE
Table borders - dashed

### ISSUE THREAD

**Issue by lofcz** [onizet/html2openxml#178]
**Describe the bug**
Currently, dashed table borders are not supported. I think there is a "dashed line" option available in openxml we could use to emulate the style? http://officeopenxml.com/WPtableBorders.php

**Repro**
```html
<table>
<tr>
  <td>cell A</td>
  <td>cell B</td>
</tr>
</table>

<style>
td {
  border: 1px dashed #bbb;
  padding: 5px 10px;
}
</style>
```

**Comment by onizet** [comment]
Dashed border is supported, it's more the tag `style` that is not. Please read the documentation about [Inlining the Css](https://github.com/onizet/html2openxml/wiki/Style)

**Comment by lofcz** [comment]
Thanks for the link, sorry!
