### ISSUE TITLE
Table column widths as a percentage

### ISSUE THREAD

**Issue by pauldbentley** [onizet/html2openxml#19]
Given `<td style="width: 100px;">` the OpenXml generated is `<w:tcW w:w="1500" w:type="dxa"/>` which works perfectly.

However, given `<td style="width: 25%;">` the OpenXml generated `<w:tcW w:w="0" w:type="pct"/>`

**Comment by pauldbentley** [comment]
I have narrowed this down to `private void ProcessTableColumn(HtmlEnumerator en)` in `HtmlConverter` which has the line:

```
case UnitMetric.Percent:
   properties.TableCellWidth = new TableCellWidth() { Type = TableWidthUnitValues.Pct, Width = (unit.ValueInDxa * 50).ToString(CultureInfo.InvariantCulture) };
   break;
```

So this uses `unit.ValueInDxa * 50` as the width, but `ValueInDxa` is `0` because `Unit.ComputeInEmus()` has the line `case UnitMetric.Percent: return 0L; // not applicable`

`unit.Value` is parsed correctly via `Unit unit = en.StyleAttributes.GetAsUnit("width");`

Could the code above be changed to use `unit.Value` instead of `unit.ValueInDxa`:

```
case UnitMetric.Percent:
   properties.TableCellWidth = new TableCellWidth() { Type = TableWidthUnitValues.Pct, Width = (unit.Value * 50).ToString(CultureInfo.InvariantCulture) };
   break;
```

**Comment by onizet** [comment]
Hello Paul,

Glad to see you back :)
I'm working on the next version (dev branch), and I already received a [PR for that error](https://github.com/onizet/html2openxml/commit/0ac34a8d3e8e67de31c755a0da48c97e3ac410e8#diff-fe9644e3c626b56102c538491794d18e) from jheine.
I'd like to release a new version soon with all these major fixes.
If you have a few spare time, I will be happy to have some help on some opened tickets :)

**Comment by pauldbentley** [comment]
Hey,

Ah I should have looked there, didn’t realise there was a dev branch (I’m not 100% up to speed on how GitHub works yet) looks like we got to the same conclusion though...

Any ETA on the new release?

**Comment by onizet** [comment]
I hope for end of Feb.
