### ISSUE TITLE
Outputs to a content control, instead of the whole document

### ISSUE THREAD

**Issue by stevebeauge** [onizet/html2openxml#2]
Hello,

In order to create templated word documents, it would be nice if the library allows generating content in a named content control, instead of the full document.

I don't think it is yet possible, isn't it?

If so, this would be a great enhancement.

thanks,
steve

**Comment by onizet** [comment]
Hello Steve,

I imagine you are dealing with some _basic_ HTML (no footnote for example).
If so, I suggest you to use HtmlConverter.Parse(String html) which gives you a list of Paragraph. You can then find your named content control and insert the paragraph inside using plain OpenXml.

Olivier

**Comment by stevebeauge** [comment]
Thanks @onizet. That seems to be exactly what I need.
