### ISSUE TITLE
Table Cell Shading Applies to Subsequent Cells

### ISSUE THREAD

**Issue by robwade** [onizet/html2openxml#20]
When HtmlConverter.ProcessClosingTableColumn calls TableStyleCollection.ApplyTags, it copies TableCellProperties from preceding cells into the one currently being processed.  For the table below, this logic results in every cell having a grey (d5d5d5) background

&lt;table style="width: 100%;"&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;th style="background-color: #d5d5d5;"&gt;Component&lt;/th&gt;
&lt;th style="background-color: #d5d5d5;"&gt;Area&nbsp;m&sup2;&lt;/th&gt;
&lt;th style="background-color: #d5d5d5; text-align: right;"&gt;%&lt;/th&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="width: 40%; text-align: left;"&gt;&nbsp;&lt;/td&gt;
&lt;td style="width: 30%; text-align: right;"&gt;&nbsp;&lt;/td&gt;
&lt;td style="width: 30%; text-align: right;"&gt;&nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="width: 40%; text-align: left;"&gt;Total&lt;/td&gt;
&lt;td style="width: 30%; text-align: right;"&gt;&nbsp;&lt;/td&gt;
&lt;td style="width: 30%; text-align: right;"&gt;100.0&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

**Comment by robwade** [comment]
The issue seems to stem from HtmlCoverter.ProcessTableColumn where the styles are queued twice:
`htmlStyles.Tables.ProcessCommonAttributes(en, styleAttributes);`
`if (styleAttributes.Count > 0)`
    `htmlStyles.Tables.BeginTag(en.CurrentTag, styleAttributes);`

**I've kept `htmlStyles.Tables.ProcessCommonAttributes(en, styleAttributes);` and deleted the other two lines.  The table is rendering correctly now.**

Just to be sure that it's not going to break when styles are missing, I've tested it with the table above and this table:
&lt;table style="width: 100%;"&gt;
&lt;tbody&gt;
&lt;tr&gt;
&lt;th style="background-color: #d5d5d5;"&gt;Component&lt;/th&gt;
&lt;th style="background-color: #d5d5d5; text-align: right;"&gt;Area&nbsp;m&sup2;&lt;/th&gt;
&lt;th style="background-color: #d5d5d5; text-align: right;"&gt;%&lt;/th&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="width: 40%; text-align: left;"&gt;&nbsp;&lt;/td&gt;
&lt;td style="width: 30%; text-align: right;"&gt;&nbsp;&lt;/td&gt;
&lt;td style="width: 30%; text-align: right;"&gt;&nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;Total&lt;/td&gt;
&lt;td&gt;&nbsp;&lt;/td&gt;
&lt;td&gt;100.0&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;

**Comment by onizet** [comment]
Hello Rob,

Thank you for your feedback. Your fix is a bit extreme :-)
May I suggest you an alternative, in TableStyleCollection, line 94.
Replace

```c#
if (!colorValue.IsEmpty && en.CurrentTag.Equals("<td>", StringComparison.OrdinalIgnoreCase)) colorValue = HtmlColor.Empty;
```

by

```c#
if (!colorValue.IsEmpty && (en.CurrentTag.Equals("<td>", StringComparison.OrdinalIgnoreCase)
	|| en.CurrentTag.Equals("<th>", StringComparison.OrdinalIgnoreCase)))
	colorValue = HtmlColor.Empty;
```

Anyways, thank you for having found that bug. I'm committing this changes.
