### ISSUE TITLE
<blockquote> Style lookup not working for "IntenseQuote"

### ISSUE THREAD

**Issue by peteamundson** [onizet/html2openxml#22]
In the default template for the latest version of Word (O365) it seems that the name for the intense quote is now "Intense Quote" with a space.  The current functionality of ProcessBlockQuote should be updated to check for both "IntenseQuote" and "Intense Quote" and then apply when one is found.  Otherwise, could this be something configurable where the block quote style is optionally passed into the conversion process?

**Comment by onizet** [comment]
Hello Pete,

I really thank you for your troubleshooting.

I'm using Word in French and for me, the style "Intense Quote" = "Citation intense".
So I don't rely on the localized name of the style. Instead, you can rely on the StyleId which doesn't vary. This is why you can see "IntenseQuote" without spacing.

**Comment by peteamundson** [comment]
I see. I did some additional testing and once the style was defined in the document (instead of the local template), then it was available to use with the "IntenseQuote" name.  This means that someone creating a document will need to adjust the style (in my original test, I renamed it) so that it is stored in the document and can be looked up by the StyleId.  I'm curious what you think about the latest changes where I am checking for the style before BeginTag call.

**Comment by onizet** [comment]
Well after the discussion of yesterday, I've reviewed all my code to automatically insert the missing style.
Some style name referenced in the code are also not accurate because it use the display name (footnote and endnote).
I will commit soon a fix but I'm still running some tests to avoid regression.

Anyways, I'm grateful for your feedback and to have spot that.

**Comment by peteamundson** [comment]
This fix looks good, thanks!
