### ISSUE TITLE
Wrong table creation

### ISSUE THREAD

**Issue by advapiIT** [onizet/html2openxml#29]
Hello,
I've got some issue with HTML Table and Docx creation... in particular I've attached you a demo project that shows the behavior (I've been unable to upload on git since I got error from this machine)

[https://drive.google.com/open?id=1dTsMoPqBHzgrbbZbvLRp_KMnojAHNeik](url)

What happens is that the content I've inside the content.html is ok (in real case this data is taken from DB), btw the HTML is correct and it shows fine.

After I add it to the document I got  this result

![image](https://user-images.githubusercontent.com/4690086/38272306-26a59418-3789-11e8-86cb-a64f6c4eb1fa.png)

instead of

![image](https://user-images.githubusercontent.com/4690086/38272323-32e648c6-3789-11e8-945c-ad195f478f7f.png)

What am I doing wrong?
Thanks

P.S. I'm using your latest version

**Comment by onizet** [comment]
Hi,

Thank you for your project, it helped me out to troubleshoot. I see that you are using the style "background". Could you try with background-color instead please? This will fix your problem.
I will keep this issue open to remember to handle just "background"

**Comment by advapiIT** [comment]
Hello ozinet,
Thanks for your fast reply, your suggestion works but consider I get this HTML from a WYSIWYG editor and I think I can't pilot it directly... what comes to my mind is to replace in the text background with background-color with a Replace...  but I've not understood, do you plan to fix it? have u got a ETA?
Thanks

**Comment by advapiIT** [comment]
Excuse me,
The feedback you gave me permitted me to go ahead with testing... With this file the result is a mess...is it due to the fact that the HTML I got is from MSWord as well?

[content_2.zip](https://github.com/onizet/html2openxml/files/1881525/content_2.zip)
Thanks
