### ISSUE TITLE
save open xml  tags in database

### ISSUE THREAD

**Issue by angel-r** [onizet/html2openxml#34]
It is possible to obtain an xml similar to this: 
`<w:p>
  <w:r>
    <w:t>My paragraph</w:t>
  </w:r>
</w:p>`

I need to save that in the database

**Comment by onizet** [comment]
Hello Angel,

This library convert an Html to OpenXML. But anytime, you can access the whole document with the official [OpenXml library](https://www.nuget.org/packages/DocumentFormat.OpenXml/).
What do you want to obtain: the whole document or just a part of it?
