### ISSUE TITLE
Symbols in HTML cannot convert correctly

### ISSUE THREAD

**Issue by Terry-Lin** [onizet/html2openxml#37]
My original HTML contains symbols such as ◎▕ . These symbols were going to become blank box in docx after converted. 
![image](https://user-images.githubusercontent.com/5515254/45204491-00137c80-b2b2-11e8-807a-9b30a17b8cd7.png)

Is there any ways to process these symbols in the code or library?

**Comment by onizet** [comment]
Sorry can't reproduce the bug
