### ISSUE TITLE
"Strong name signature could not be verified" for version 2.0.2

### ISSUE THREAD

**Issue by gh5692** [onizet/html2openxml#39]
I'm getting the following error with version 2.0.2:

> [FileLoadException: Could not load file or assembly 'HtmlToOpenXml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6ad79d83e2b60e63' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]

I used NuGet to get the package and the build target is .Net Framework 4.7. Version 2.0.1 works without issue.

**Comment by seguso** [comment]
same here

**Comment by matif1988** [comment]
![image](https://user-images.githubusercontent.com/22295804/49305828-ab5a5900-f4d0-11e8-8bed-f5317687781d.png)

Any one can help me please!!

**Comment by ole1986** [comment]
Same here

**Comment by onizet** [comment]
Fix in 2.0.3
