### ISSUE TITLE
Style table using HtmlConverter in c#

### ISSUE THREAD

**Issue by Geek-5** [onizet/html2openxml#43]
A predefined string with the following style <table border=\"1\", has been defined within the database.  Can I use the HtmlConverter class to modify the style within the table tag?

**Comment by onizet** [comment]
Hello, this is mainly a library for parsing then converting.
To modify the Html, I will recommend you HtmlAgilityPack instead

**Comment by Geek-5** [comment]
Thank you for the recommendation. It worked great!

**Comment by Geek-5** [comment]
If a table element  <table> is stripped of all its attributes and passed through the ParseHtml method, should the HtmlToOpenXml.TableContext field tables be populated with the table element?
