### ISSUE TITLE
bordercolor attribute not being parsed 

### ISSUE THREAD

**Issue by Geek-5** [onizet/html2openxml#44]
Within a table tag, the bordercolor attribute is not parsed:
<table border-color="#FFFFFF"></table>

Inline css does not work either : (border: 1px solid black)

Will there be any support for this?

**Comment by onizet** [comment]
Honestly, I don't have much time to invest on this library. If you submit a PR, I will merge it

**Comment by Geek-5** [comment]
Ok.

**Comment by onizet** [comment]
Closing as this is supported v2.3
