### ISSUE TITLE
word experienced an error trying to open the file Error

### ISSUE THREAD

**Issue by saamtehraani** [onizet/html2openxml#47]
I have tried to convert HTML to OpenXML. When I want to open the generated file I get this error:

![image](https://user-images.githubusercontent.com/3000791/57189676-ae141b00-6f54-11e9-819d-044620754be1.png)

This is my code:

                    string background = ((dynamic)obj).Entity.Background as string;                    
                    HtmlConverter converter = new HtmlConverter(mainDocumentPart);
                    IList<OpenXmlCompositeElement> convertedToHTML = converter.Parse(background);
                    List<OpenXmlElement> openXmlElementList = new List<OpenXmlElement>();

                    convertedToHTML.ToList().ForEach(q =>
                    {
                        var convertedOpenXmlElement = q as OpenXmlElement;
                        openXmlElementList.Add(convertedOpenXmlElement);
                    });

                    addAction(new Run(convertedToHTML.ToList()));

**Comment by saamtehraani** [comment]
Solved

**Comment by luisromerodev** [comment]
I am facing similar issue. seems like html is not right ? any thoughts how do you resolved ?
