### ISSUE TITLE
Error with class attribute handling

### ISSUE THREAD

**Issue by stevebeauge** [onizet/html2openxml#5]
I'm trying to convert HTML with some formatting (applied through class attributes) to word content.

The html content is:

```
<div>
    <strong>Bold<span class="red-characters">red bold</span></strong>
    <span class="red-characters">red</span><span>No formatting</span>
</div>
```
The html result is:
![html](https://user-images.githubusercontent.com/184604/28774540-2bd3d86c-75ee-11e7-9366-0411f493d366.PNG)

However, after conversion, the result is:

![word](https://user-images.githubusercontent.com/184604/28774590-6cb4bc8e-75ee-11e7-99e4-345a1c378023.PNG)

In order to have the red formatting available in Word, I created a new character style named `red-characters`, and changed its color.

A full reproductible sample is added as attachments: [TestHtmlToWordMl.zip](https://github.com/onizet/html2openxml/files/1187269/TestHtmlToWordMl.zip)

How to properly handle this scenario ?

Thanks

**Comment by stevebeauge** [comment]
My issue occurs with the Nuget package (v1.6.1).

If I compile the source code and use the generated DLL, it works as expected.

Maybe the nuget package should be updated ?

Thanks

**Comment by onizet** [comment]
Yes it really should but I'm quite a beginner on producing a nuget and I don't have a lot of free time. If you want to help, I will be happy :-)

**Comment by stevebeauge** [comment]
Unfortunately, I never had the opportunity to explore nuget publishing, sorry.

**Comment by onizet** [comment]
Release v2.0 has been released
