### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by nfgallimore** [onizet/html2openxml#65]
How can I give you a small donation, put a link in readme? Really helpful library that saved me LOTS of time. Maybe use https://www.buymeacoffee.com/

**Comment by onizet** [comment]
Hello Nick,

I really appreciate your proposition but I'm not not seeking for money.
In the past, I received some money from Ads on Codeplex but refund everything to animal causes.

Nowadays, I don't have much time to invest on this project. So I'm more looking for PR to fix the opened bugs.
Thank you anyway for your support :)
