### ISSUE TITLE
RTL support for (Hebrew, Arabic)

### ISSUE THREAD

**Issue by yonihbc** [onizet/html2openxml#66]
I'm trying to change text direction to right-to-left 

i don't see any support for that

please help,

**Comment by onizet** [comment]
Actually, it offers some very basic support on RTL. In the past, I invested some time on this topic but was lacking of real testing cases. And in the end, I'm sorry to say that but it was very few requested.
But if you want to submit a PR, I will more than willing to merge it

**Comment by wsaeed123** [comment]
I exported RTL content, the content is exported RTL fine  ,but the paper setting itself still  LTR. 

it will be much appreciated if you help.
thank you
