### ISSUE TITLE
HTML <b> is not working as well as css Font-weight property

### ISSUE THREAD

**Issue by anshumandikshit** [onizet/html2openxml#67]
The HTML <b> tag is not getting parsed .I have also checked with style='font-weight: 500;font-weight: bold;' . But both are not working properly .Any leads will be very helpful for me .

`<label ><b> <span> Degree  :</span> </b> <span>Something</span></label><br/>`

`<label > <span style='font-weight: 500;font-weight: bold;'> Degree :  </span>  <span>Something </span></label><br/>`

The generated output snapshot has been attached in image 

![IssueBoldHtml](https://user-images.githubusercontent.com/12956424/77651636-16b41e00-6f93-11ea-8bdd-5e444bf422d6.PNG)

**Comment by onizet** [comment]
Remove the space `<label >` -> `<label>` 

I did the test and it works fine if modified
