### ISSUE TITLE
Not working with the latest version of OpenXML

### ISSUE THREAD

**Issue by Christian1980** [onizet/html2openxml#68]
Hi,

I have a project using your dll (via nuget packages). All is fine but when I try to update to the latest version of DocumentFormat (2.10.1) it complains about the DocumentFormat has not the right definition in the manifest assembly. So I need to downgrade DocumentFormat back to 2.7.2

'Unable to load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. Definition found in the assembly manifest does not match the assembly reference. (Exception de HRESULT : 0x80131040)'

The only solution would be to rebuild your dll myself from the source code with the latest version of DocumentFormat. Is it not possible to use DocumentFormat without being stuck to a particular version ?

**Comment by twsouthwick** [comment]
Hi - I'm one of the maintainers of OpenXml. It appears that this library has been using an internal method that I removed recently. Not sure who the maintainer of this project is, but I'm happy to work with you to add a proper API that will be supported and not pulled out from under you! Sorry about that, but it was part of some deep rearchitecture work. I can't just re-add it as the concept it was supporting isn't even there anymore.

Feel free to file an issue at OpenXml to get a fix into the next minor version. I'll need the scenario you're trying to solve (there may also be a better way to do it). Also, feel free to open a PR to list your project on the README as related projects!

**Comment by twsouthwick** [comment]
What framework are you running on? This sounds like a binding redirection issue. Happy to help if you describe how you're running this.
