### ISSUE TITLE
Using removed internal API from OpenXml >= 2.11.0

### ISSUE THREAD

**Issue by twsouthwick** [onizet/html2openxml#70]
Hi - I'm one of the maintainers of OpenXml. It appears that this library has been using an internal method that I removed recently. I'm happy to work with you to add a proper API that will be supported and not pulled out from under you! Sorry about that, but it was part of some deep rearchitecture work. I can't just re-add it as the concept it was supporting isn't even there anymore.

Feel free to file an issue at OpenXml to get a fix into the next minor version. I'll need the scenario you're trying to solve (there may also be a better way to do it). Also, feel free to open a PR to list your project on the README as related projects!

**Comment by onizet** [comment]
Hi Taylor, thank you for providing an alternative and even more a PR. This is much appreciate.
Sorry for the test case about EMF, I should have deleted that case because it is already handled in another test.
