### ISSUE TITLE
Parameter count mismatch

### ISSUE THREAD

**Issue by shashankgwl** [onizet/html2openxml#74]
I'm using the default HTML sample provided in the documentation, I'm running it with .NET FX 4.6.2, I get below error when I use  `converter.ParseHtml(html)`

Am I doing anything wrong??

![image](https://user-images.githubusercontent.com/2750603/88694452-2ba9e500-d11e-11ea-9b61-df2f0d893cd8.png)

**Comment by onizet** [comment]
Hi,

There was a recent release about this issue. You could follow the discussion here #70.  
I will release soon a new release to support back .Net Standard 1.3 and .Net Framework 4.6. Until then, or you could downgrade your OpenXML dependency, or use release 2.1.0
