### ISSUE TITLE
Unorder list transformed into order list

### ISSUE THREAD

**Issue by ericadcg** [onizet/html2openxml#82]
Hello.
I have an unorder list (\<ul> ) in my html and it's getting turned into an ordered list when the word is generated. 

I checked the code and both tags \<ul> and \<ol> are using the ProcessNumberingList and BeginList.
I have tried to make a new BeginList to use \<ul> instead of \<ol> but it did not work properly.

Any ideas?

**Comment by nascimento3** [comment]
Hi,

I'm having exactly the same problem...

@onizet any ideas? 

Thanks!

**Comment by onizet** [comment]
Do you use a fresh new document or insert into an existing one? I ran the Demo project and do not see any issues regarding `<ul>`. Could you post more details for troubleshooting?

**Comment by ericadcg** [comment]
Thank you for your reply.
The problem happens when there is a list inside a list, example:
```Code:  
<table>
    <tbody>
		<tr>
			<th>
			Header
			</th>
		</tr>
		<tr>
			<td> 
				<ul>
					<li>This is a test item - First List
						<ul>
							<li>Second List</li>
						</ul>
					</li>
				</ul>
			</td>
		</tr>	
	</tbody>
</table>
```

If I don't have the html shown above, everything is ok. But if I do, that list is ok, but all the following unorded lists are shown as orderd. Example:
```
<table>
    <tbody>
		<tr>
			<th>
			Header
			</th>
		</tr>
		<tr>
			<td> 
				<ul>
					<li>This is a test item - First List
						<ul>
							<li>Second List</li>
						</ul>
					</li>
				</ul>
			</td>
		</tr>	
	</tbody>
</table>


<table>
  <tbody>
    <tr>
       <td>Header 2</td>
   </tr>
    <tr>
       <td>
<ul><li>Test</li></ul>
<table> 
    <tr>
        <td style = 'width: 5%;'></td>
        <td style = 'width: 95%;'>
            <table>
                <tr>
                    <td style='padding-left: 30px;'>Test 2

                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</table>
```

Here is an image of the word output of the html from above:

![WordOutputExample](https://user-images.githubusercontent.com/70650310/95333984-68742400-08a5-11eb-91ae-c48f2823f16c.PNG)

**Comment by ericadcg** [comment]
Here is a simpler example (with less tables involved):

```
<html>
    <body>
<p>Paragraph<p>
<ul>
	<li> This is a test item </li>
	<ul>
		<li> Second List</li>
	</ul>	
</ul>


<p>Paragraph 2</p>
<ul>
	<li>New ul list - item 1</li>
	<li>item 2</li>
</ul>
	
</body>
</html>
```

And this is the word output for the html above:
![WordOutputExample2](https://user-images.githubusercontent.com/70650310/95340166-be989580-08ac-11eb-8179-51019b7f361b.PNG)

Also, I'm using a fresh new document.

Thank you again!

**Comment by dhavalgajera** [comment]
In NumberingListStyleCollection

possible fix can be following:

`     public void EndList(bool popInstances = true)
        {
            levelDepth--;

            if (levelDepth > 0 && popInstances)
                numInstances.Pop();  // decrement for nested list

            firstItem = true;
        }`

**Comment by sbowler** [comment]
I ran into this issue as well throwing together a couple different lists and nested lists to test out the HtmlConverter. This seems to result in all lists being styled as ordered lists for some reason. Maybe this is a different bug, but sounds like maybe it is the same issue. Here is the example HTML and an example resulting paragraph. Thanks for the work on this library.
```
<ul class="alternate" type="square">\n\t
  <li>dfdf\n\t
    <ul class="alternate" type="square">\n\t\t
      <li>dfdfa</li>\n\t
    </ul>\n\t
  </li>\n\t
  <li>dfd</li>\n
</ul>
<br/>\n
<ul>\n\t
  <li>foof\n\t
    <ul>\n\t\t
      <li>fkfjf</li>\n\t
    </ul>\n\t
  </li>\n\t
  <li>adsf</li>\n
</ul>
<br/>\n
<ol>\n\t
  <li>num 1</li>\n\t
  <li>num 2</li>\n
</ol>\n
```
```
<w:p xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:pPr>
	<w:pStyle w:val="ListParagraph"/>
	<w:numPr>
		<w:ilvl w:val="0"/>
		<w:numId w:val="2"/>
	</w:numPr>
  </w:pPr>
  <w:r>
	<w:t xml:space="preserve">dfdf</w:t>
  </w:r>
</w:p>
```

**Comment by sbowler** [comment]
For some reason even the following non-nested lists results in two numbered lists. The number count also doesn't seem to reset between different lists like you might expect. Of course it shouldn't be numbered at all. I tried instantiating a new HtmlConverter between different conversions using the same main word document part to no affect. I think @dhavalgajera suggestion would maybe help the count reset issue, but not the fact that it shouldn't be ordered to begin with.
```
<p>Verify the blah</p>
<ul>
  <li>abc</li>
  <li>dfe</li>
  <li>ghi</li>
  <li>qwe</li>
</ul>
<br/>
<p>Verify the blah2</p>
<ul>
  <li>abc</li>
  <li>def</li>
  <li>ghi</li>
  <li>qee</li>
  <li>pol</li>
  <li>zxc</li>
</ul>
```

**Comment by sbowler** [comment]
I finally got this in a state that seems to be working properly. Here is the gist of the code if it helps anyone having similar issues. In my case I was looking for certain things and then wanting to replace that paragraph with the HTML converted stuff. I've simplified it a bit for more generic code.
```
using (WordprocessingDocument package = WordprocessingDocument.Open(outputFilePath, true))
{
  MainDocumentPart mainPart = package.MainDocumentPart;
  if (mainPart == null)
  {
    // You may just want to create an empty document here for your case
    throw new Exception("Document appears to be empty");
  }

  HtmlConverter converter = new HtmlConverter(mainPart);
  foreach (var paragraph in mainPart.Document.Body.Descendants<DocumentFormat.OpenXml.Wordprocessing.Paragraph>())
  {
    if (paragraph.InnerText.Contains("FOO"))
    {
      foreach (var node in converter.Parse(foo.HtmlStep).Reverse())
      {
        paragraph.InsertAfterSelf(new Paragraph(node.OuterXml));
      }

      paragraph.Remove();
    }
  }

  mainPart.Document.Save();
}
```

**Comment by juan25d** [comment]
@onizet Hi I am still faicing this issue, when adding 2 list in a single document.

The HTML that i have is the following:

`<html><body><h3>Admininistrative Boundaries</h3><ul><li>Boundaries A</li><li>Boundaries B</li></ul><h3>Architectural Conservation Areas</h3><ul><li>Conservation Area A</li><li>Conservation Area B</li></ul></body></html>`

What I do is convert this HTML to OpenXML elements using your conversor:

            WmlDocument doc = HtmlToWmlConverter.ConvertHtmlToWml(defaultCss, htmlCss, string.Empty, html, settings, null, null);

            using (OpenXmlMemoryStreamDocument streamDoc = new OpenXmlMemoryStreamDocument(doc))
            {
                using (WordprocessingDocument document = streamDoc.GetWordprocessingDocument())
                {
                    result = document.MainDocumentPart.Document.Body.Elements().ToList();
                }
            }

Then append that elements to a paragraph in a existing word:

            List<OpenXmlElement> elements = new List<OpenXmlElement>();

            elements =  Helper.HtmlToOpenXML(html);

            using (WordprocessingDocument doc = WordprocessingDocument.Open(wordDocument, true))
            {
                var parentParagraph = new Paragraph();
                doc.MainDocumentPart.Document.AppendChild(parentParagraph);

                foreach (var element in elements)
                {
                    if (!(element is SectionProperties))
                    {
                        var clonedElement = element.CloneNode(true);
                        parentParagraph.InsertBeforeSelf(clonedElement);
                    }
                }

                doc.Save();
            }

The result is the following:

<img width="412" height="211" alt="Image" src="https://github.com/user-attachments/assets/6f1dc8e1-77bf-4c9d-ba31-9ff114db7811" />

Any clue?

Thanks

**Comment by onizet** [comment]
There is something fundamentally wrong in your code. This library requires an access to the hosting document but it will auto-register styles or (list) numbering.
I can see in your code that your first convert to elements (where those paragraphs include references to numbering ID) but inserts those to another documents (where the referenced number id are either missing, either not those expected).
