### ISSUE TITLE
Is it possible to add footer to every doc page?

### ISSUE THREAD

**Issue by umbarov** [onizet/html2openxml#94]
Hi,
I would like to add a company logo to every footer section of a doc file. Is it possible to do this in html?

**Comment by onizet** [comment]
Hi, the API to add content to header/footer is different than the main content.
If you want to design a static template, I suggest you to save your docx and append the result of the Html conversion into it.
You can find more in the demo code : https://github.com/onizet/html2openxml/blob/dev/examples/Demo/Program.cs

**Comment by umbarov** [comment]
@onizet thanks. 👍
