### ISSUE TITLE
ParseHtml throws exception when using Dotx styles

### ISSUE THREAD

**Issue by RoelVerhees** [onizet/html2openxml#98]
Hey guys,

After we have updated the package to the latest version, we experience errors. The package is used to go from HTML to OpenXML and we also use a DOTX file that contains custom styles.

As soon as we refer to the custom styles in the HTML, we get an error during the conversion. For referencing we use the class attribute, this works for an H1 but not for a custom style for a table.

I have rolled back the package and the problem has been fixed immediately.

**Comment by onizet** [comment]
This is now fixed
